AWSTemplateFormatVersion: "2010-09-09"
Description: Compute stack (ALB, Target Group, LaunchTemplate, ASG)

Parameters:
  AppPort:
    Type: Number
    Default: 80
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: app-alb
      Subnets:
        - !ImportValue PublicSubnetA
        - !ImportValue PublicSubnetB
      SecurityGroups:
        - !ImportValue AlbSG
      Scheme: internet-facing
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: app-tg
      Port: !Ref AppPort
      Protocol: HTTP
      VpcId: !ImportValue VpcId
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      TargetType: instance

  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
      - PolicyName: CodeDeployAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:Get*
                - s3:List*
              Resource:
                - "arn:aws:s3:::aws-codedeploy-*"
                - "arn:aws:s3:::aws-codedeploy-*/*"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: app-lt
      LaunchTemplateData:
        InstanceType: t3.micro
        IamInstanceProfile:
          Name: !Ref EC2InstanceProfile
        ImageId: !Ref LatestAmiId
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeType: gp3
              VolumeSize: 20
              DeleteOnTermination: true
        SecurityGroupIds:
          - !ImportValue Ec2SG
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y python3 git amazon-cloudwatch-agent codedeploy-agent aws-xray-daemon
            systemctl enable amazon-cloudwatch-agent codedeploy-agent xray

            # Create app folder and log file
            mkdir -p /app
            touch /app/app.log
            chmod 666 /app/app.log

            # Configure CloudWatch Agent to collect logs
            cat <<EOF >/opt/aws/amazon-cloudwatch-agent/bin/config.json
            {
              "logs": {
                "logs_collected": {
                  "files": {
                    "collect_list": [
                      {
                        "file_path": "/app/app.log",
                        "log_group_name": "/MasterProject3/app",
                        "log_stream_name": "{instance_id}/app"
                      },
                      {
                        "file_path": "/var/log/messages",
                        "log_group_name": "/MasterProject3/system",
                        "log_stream_name": "{instance_id}/messages"
                      }
                    ]
                  }
                }
              }
            }
            EOF

            # Start CloudWatch Agent
            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
              -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s

            systemctl start amazon-cloudwatch-agent codedeploy-agent xray

            # Install Python dependencies
            pip3 install flask flask-cors aws-xray-sdk

            # Create Flask app (unchanged)
            cat <<EOF >/app/app.py
            from flask import Flask, jsonify, request
            from flask_cors import CORS
            import time, random
            from aws_xray_sdk.core import xray_recorder
            from aws_xray_sdk.ext.flask.middleware import XRayMiddleware
            from aws_xray_sdk.core import patch_all

            app = Flask(__name__)
            CORS(app)
            patch_all()

            xray_recorder.configure(service='MasterProjectAPI', sampling=True)
            XRayMiddleware(app, xray_recorder)

            @app.route("/test-trace")
            def test_trace():
                subsegment = xray_recorder.begin_subsegment('manual')
                xray_recorder.end_subsegment()
                return "trace test", 200

            @app.route("/health")
            def health():
                return "ok", 200

            @app.route("/items")
            def items():
                count = int(request.args.get("count", 10))
                time.sleep(random.uniform(0.05, 0.2))
                data = [{"id": i, "name": f"item-{i}"} for i in range(count)]
                return jsonify(data), 200

            @app.route("/error")
            def error():
                return "error", 500

            app.run(host="0.0.0.0", port=${AppPort})
            EOF

            # Start Flask app
            if [ "${AppPort}" -lt 1024 ]; then
              sudo python3 /app/app.py >> /app/app.log 2>&1 &
            else
              python3 /app/app.py >> /app/app.log 2>&1 &
            fi

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 2
      MaxSize: 6
      DesiredCapacity: 2
      VPCZoneIdentifier:
        - !ImportValue PrivateSubnetA
        - !ImportValue PrivateSubnetB
      TargetGroupARNs:
        - !Ref TargetGroup

Outputs:
  AlbArn:
    Description: ALB ARN
    Value: !Ref Alb
    Export:
      Name: AlbArn

  AlbName:
    Description: ALB full name (for CloudWatch dimensions)
    Value: !GetAtt Alb.LoadBalancerFullName
    Export:
      Name: AlbName

  AlbDNS:
    Description: ALB DNS name
    Value: !GetAtt Alb.DNSName
    Export:
      Name: AlbDNS

  TargetGroupArn:
    Description: Target Group ARN
    Value: !Ref TargetGroup
    Export:
      Name: TargetGroupArn

  AutoScalingGroupName:
    Description: ASG Name
    Value: !Ref AutoScalingGroup
    Export:
      Name: AsgName
