AWSTemplateFormatVersion: "2010-09-09"
Description: Observability stack (CloudWatch Metrics and Alarms)

Parameters:
  MetricNamespace:
    Type: String
    Default: MasterProject3
  AppErrorThreshold:
    Type: Number
    Default: 1
  Alb5xxThreshold:
    Type: Number
    Default: 1

Resources:
  # Metric filters on existing log groups
  AppErrorMetricFilterApp:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: "/MasterProject3/app"
      FilterPattern: ?error
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: !Ref MetricNamespace
          MetricName: AppErrorCount

  AppErrorMetricFilterSystem:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: "/MasterProject3/system"
      FilterPattern: ?error
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: !Ref MetricNamespace
          MetricName: AppErrorCount

  # CloudWatch alarms
  AppErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: AppErrorAlarm
      Namespace: !Ref MetricNamespace
      MetricName: AppErrorCount
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: !Ref AppErrorThreshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []

  Alb5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Alb5xxAlarm
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_ELB_5XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !ImportValue AlbName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: !Ref Alb5xxThreshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []

Outputs:
  AppErrorAlarmName:
    Description: "CloudWatch Alarm for App Errors"
    Value: !Ref AppErrorAlarm
    Export:
      Name: AppErrorAlarmName

  Alb5xxAlarmName:
    Description: "CloudWatch Alarm for ALB 5xx Errors"
    Value: !Ref Alb5xxAlarm
    Export:
      Name: Alb5xxAlarmName
